import React from 'react';

const TermsPage: React.FC = () => {
  return (
    <main className="flex-1 bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24 max-w-4xl">
        <div className="mb-12">
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
            <p className="text-gray-500">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="prose prose-lg prose-indigo max-w-none text-gray-600">
            <p className="lead text-lg text-gray-700 mb-8">
                Please read these Terms of Service ("Terms") carefully before using the LuminaScale website and application operated by us.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h3>
            <p className="mb-4">
                By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">2. Use License</h3>
            <p className="mb-4">
                Permission is granted to temporarily use LuminaScale for personal, non-commercial image enhancement. Under this license, you may not:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>Use the service for any illegal or unauthorized purpose.</li>
                <li>Attempt to decompile or reverse engineer any software contained in the LuminaScale application.</li>
                <li>Remove any copyright or other proprietary notations from the materials.</li>
                <li>Upload content that infringes on the intellectual property rights of others.</li>
            </ul>

            <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">3. Disclaimer</h3>
            <p className="mb-4">
                The materials on LuminaScale are provided on an 'as is' basis. We make no warranties, expressed or implied, and hereby disclaim and negate all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">4. Limitations</h3>
            <p className="mb-4">
                In no event shall LuminaScale or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on LuminaScale, even if we have been notified orally or in writing of the possibility of such damage.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">5. AI Output</h3>
            <p className="mb-4">
                You acknowledge that the enhanced images are generated by Artificial Intelligence. While we strive for high quality, the output may occasionally contain artifacts, hallucinations, or inaccuracies. You are responsible for reviewing the output before using it.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">6. Changes</h3>
            <p className="mb-4">
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion.
            </p>
        </div>
      </div>
    </main>
  );
};

export default TermsPage;